# -- [ aliases ] ---------------------------------------------------------------
# git
alias gp="git push origin"
alias gpr="git pull --rebase"
alias gb="git branch"
alias gc="git commit"
alias ga="git add"
alias gco="git checkout"
alias gcb="git checkout -b"
alias gc-="git checkout --"
alias gs="git status"
alias gl="git log --oneline"
alias gln="git log --oneline -n"
alias gst="git stash"
alias gsa="git stash apply"
alias gf="git fetch -p"
alias gm="git merge"
alias gmd="git merge --no-ff origin/develop"
alias gdf="git diff"
alias gmc="git clone --recurse-submodules"
alias gmu="git submodule update --remote"

# docker compose
alias dcb="docker-compose build"
alias dcu="docker-compose up -d"
alias dcd="docker-compose down"
alias dce="docker-compose exec"
alias dcps="docker-compose ps"
